//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThucAnNhanh.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public MONAN()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public string MaMonAn { get; set; }
        [Required(ErrorMessage = "Tên món ăn không được để trống")]
        [StringLength(50, MinimumLength = 2)]
        public string TenMonAn { get; set; }
           [Required(ErrorMessage = "Giá tiền phải từ 1000 VND-2000000 VND")]
        [Range(1000, 2000000)]
        public Nullable<double> GiaTien { get; set; }
        [Required]
        public string Anh { get; set; }
        [Required]
        public Nullable<int> MaLoaiMonAn { get; set; }
        [Required(ErrorMessage = "Số lượng lớn hơn 1 và <2000000")]
        [Range(0, 2000000)]
        public Nullable<int> SoLuong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD> CTHDs { get; set; }
        public virtual LOAIMONAN LOAIMONAN { get; set; }
    }
}
