//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HDs = new HashSet<HD>();
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
    
        public string MaNhanVien { get; set; }
     
        public string HoNhanVien { get; set; }
        [Required(ErrorMessage = "Nhập tên nhân viên")]
        public string TenNhanVien { get; set; }
        [Range(0, Int32.MaxValue,ErrorMessage = "Bạn phải nhập số")]
        public string SDT { get; set; }
        [Required]
        [Display(Name = "Ngày Sinh")]
        [DataType(DataType.Date)]
        [DOBDateValidation]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
      
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD> HDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
