//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class QUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QUYEN()
        {
            this.TAIKHOANs = new HashSet<TAIKHOAN>();
        }
        [NotMapped]
        public List<QUYEN> ListQuyen { get; set; }
        [Required(ErrorMessage = "Nhập mã quyền")]
        public string MaQuyen { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên quyền")]
        public string TenQuyen { get; set; }
        [Required(ErrorMessage = "Nhập true nếu là quản lý, dif nếu là nhân viên và admin nếu là quản trị viên")]
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAIKHOAN> TAIKHOANs { get; set; }
    }
}
