//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCuaHangThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TAIKHOAN
    {
        public string ID { get; set; }
        [Required(ErrorMessage = "Vui lòng điền tên tài khoản")]
        [StringLength(50, MinimumLength = 3)]
        public string TenTaiKhoan { get; set; }
        [Required(ErrorMessage = "Vui lòng điền Mật khẩu")]
        //[RegularExpression(@"^(?=.[a-z])(?=.[A-Z])(?=.*\d).{8,15}$")]
        public string MatKhau { get; set; }
        [Required]
        public string MaQuyen { get; set; }
        public string MaNhanVien { get; set; }
        public List<SelectListItem> lstQuyen { get; set; }

        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual QUYEN QUYEN { get; set; }
    }
}
